Update manual.yml

diff --git a/.github/workflows/manual.yml b/.github/workflows/manual.yml
--- a/.github/workflows/manual.yml
+++ b/.github/workflows/manual.yml
@@ -20,7 +20,10 @@ jobs:
         fi
         for REQ_FILE in $REQ_FILES; do
           echo "Installing packages from $REQ_FILE"
-          pip install -r "$REQ_FILE"
+          pip install -r "$REQ_FILE" || {
+            echo "Error installing packages from $REQ_FILE"
+            exit 2
+          }
         done
         
     - name: Execute Python scripts
